# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '美团外卖练习' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'SDWebImage'
pod 'SVProgressHUD'

end
